[package]
name = "score"
version = "0.1.0
cairo-version = "2.9.4"

[dependencies]
starknet = "2.2.0"
openzeppelin_access = "1.0.0"

[[target.starknet-contract]]
casm = true
sierra = true
casm-add-pythonic-hints = true